### ISSUE TITLE
Programming Assignment 5.2

### ISSUE THREAD

**Issue by peteraw** [PrincetonUniversity/Coursera-SDN#28]
Guys this is very sloppy. I have re-clone and rebuild vagrant. There is no ~/p4factory and all the corresponding make files that comes with it.

vagrant@coursera-sdn:~/p4factory/targets/simple_router_acl$ make
Makefile:23: ../../init.mk: No such file or directory
Makefile:34: /home/vagrant/p4factory/targets/simple_router_acl/../../makefiles/common.mk: No such fi
le or directory
make: **\* No rule to make target `/home/vagrant/p4factory/targets/simple_router_acl/../../makefiles/
common.mk'.  Stop.

**Comment by feamster** [comment]
You probably need to reprovision your VM if you're missing the directory.  This is not the place for unconfirmed bugs.  Use Piazza to post problems you are having with your own assignment, not github. Closing this, as it's not an actual bug.
