### ISSUE TITLE
Failed to clone Coursera SDN on my OS X maverick

### ISSUE THREAD

**Issue by raxroblade** [PrincetonUniversity/Coursera-SDN#40]
after installed and confirmed i got this issue. Can you tell me what i need to do to get it fixed?
![issue1](https://cloud.githubusercontent.com/assets/13239065/8573073/5be8730a-2555-11e5-988c-5b5328cfd427.jpg)

**Comment by agupta13** [comment]
This should go in Piazza not on Github issue tracker. Please read Piazza and instructions before posting anything here.
