### ISSUE TITLE
Mismatch of policy naming by NuSMV and kinetic_gardenwall.py

### ISSUE THREAD

**Issue by thiagolckurovski** [PrincetonUniversity/Coursera-SDN#46]
kinetic_gardenwall.py's NuSMV properties are written assuming that the policies will be named by NuSMV this way:

policy_1: redirect
policy_2: drop
policy_3 identity

In practice, I wasn't able to make it name them like that. It consistently detects them like this:

policy_1: identity
policy_2: redirect

Drop is detected as just drop.

```
MODULE main
  VAR
    policy      : {policy_1,policy_2,drop};
    infected    : boolean;
    exempt      : boolean;
```

It doesn't appear among the other policies, though.

```
-- =====================================================================
-- PolicyName (used in NuSMV) to ActualPolicy (used in Pyretic) Mapping
-- =====================================================================
-- ---------------------------------------------
-- policy_1: (shown below)
-- ---------------------------------------------
-- identity
-- ---------------------------------------------
--
-- ---------------------------------------------
-- policy_2: (shown below)
-- ---------------------------------------------
-- parallel:
--     intersection:
--         sequential:
(...)
--                 else
--                     drop
-- ---------------------------------------------
```

Maybe this is intentional, but if it isn't you can change clarify kinetic_gardenwall.py to use the correct policy names in its properties by just translating (policy_1 => policy_2, policy_2 => drop, policy_3 => policy_2).

Thanks.

**Comment by wenhuizhang** [comment]
Hi, rewriteDstIPAndMAC() is not a defined function, you probably have to define it yourself.

**Comment by thiagolckurovski** [comment]
It is defined, AFAIK inside pyretic.kinetic.util.rewriting...

But that's not the issue here. The Python code is fine. It's the NuSMV directives that aren't immediately correct.
