### ISSUE TITLE
Cannot find required executable ovs-controller

### ISSUE THREAD

**Issue by Woutifier** [PrincetonUniversity/Coursera-SDN#49]
After running 'vagrant up' and ssh'ing into the box 'sudo mn' results in the following:

```
vagrant@coursera-sdn:~$ sudo mn
*** Creating network
*** Adding controller
*** Adding hosts:
h1 h2 
*** Adding switches:
s1 
*** Adding links:
(h1, s1) (h2, s1) 
*** Configuring hosts
h1 h2 
*** Starting controller

Cannot find required executable ovs-controller.
Please make sure that it is installed and available in your $PATH:
(/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
vagrant@coursera-sdn:~$
```

A 'sudo apt-get install openvswitch-controller' then results in:

```
vagrant@coursera-sdn:~$ sudo apt-get install openvswitch-controller
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 openvswitch-controller : Depends: openvswitch-common (= 2.0.2-0ubuntu0.14.04.1) but 2.3.0-1 is to be installed
                          Depends: openvswitch-pki (= 2.0.2-0ubuntu0.14.04.1) but 2.3.0-1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by feamster** [comment]
This is not a big, but an  issue with your setup.

**Comment by Woutifier** [comment]
Sorry about that. Figured it was a problem with the vagrantfile.

**Comment by cschrishoo** [comment]
how these problem was fixed?

**Comment by Woutifier** [comment]
It wasn't. You are supposed to go to Piazza, to which I could not get access, so that's where it ended for me. The course instructors apparently think this is an issue with my (our) setup (which is really their setup, because it's their Vagrantfile).

**Comment by feamster** [comment]
The Vagrantfile works fine for us and thousands of  students.

**Comment by Woutifier** [comment]
@cschrishoo in order to fix this you need to install openvswitch which can be done using the setup/ovs-setup.sh script. You just need to add it to the Vagrantfile. Then the steps that are listed in the readme of this git repository work (i.e.: sudo mn doesn't result in an error). 

This is the line that you need to add before the other provisioning lines (they look similar) in the Vagrantfile:
<code>
config.vm.provision :shell, privileged: false, :path => "setup/ovs-setup.sh"
</code>

After adding that you can run "vagrant provision" to install everything. Note that this doesn't necessarily help you with the actual course.

**Comment by feamster** [comment]
Fixed and closing.

**Comment by saeed1000** [comment]
@Woutifier  @feamster 
Hello
I faced same problem
after installing mininet 
`Cannot find required executable ovs-controller.
Please make sure that it is installed and available in your $PATH:
(/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)`
i try installing Open vSwitch but it dosen't solve the problem
I'm starter and don't know what is  Vagrantfile and the actual file path?
please help.

Ubuntu 17 64bit 
http://uploads.ru/b2Rmr.png

**Comment by tlzzz** [comment]
I have the same issue like yours in your png. Did you solve it? @saeed1000

**Comment by tlzzz** [comment]
solved.
just reinstall mininet
sudo apt-get install mininet

**Comment by PedroLuisDionisioFraga** [comment]
My solution:
```bash
sudo apt-get install openvswitch-testcontroller
sudo ln /usr/bin/ovs-testcontroller /usr/bin/controller
```

Reference: http://installfights.blogspot.com/2016/09/cannot-find-required-executable.html
