### ISSUE TITLE
I install mininet wifi i run $ sudo mn --wifi and i get problem how can I solve it pls?

### ISSUE THREAD

**Issue by harualhassan** [PrincetonUniversity/Coursera-SDN#52]
*** Creating network
*** Adding controller
Cannot find required executable ifconfig.
Please make sure that Mininet is installed and available in your $PATH:
(/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin)

**Comment by caqyflichking** [comment]
apt install net-tools
