### ISSUE TITLE
Mininet not found

### ISSUE THREAD

**Issue by partha117** [PrincetonUniversity/Coursera-SDN#54]
Hi, I have run the vagrant up command but in one phase it showed error. It is saying "Couldn't find index page for 'mininet' ". How can I fix that?
![Screenshot from 2020-05-10 08-19-47](https://user-images.githubusercontent.com/14056362/81489671-15685780-929a-11ea-82e6-adb92bb630c9.png)

**Comment by morgangraphics** [comment]
The URL for the openflow Repo is no longer valid. You'll have to replace the old URL with the new one inside the Vagrant Box mininet repo

1. `vagrant ssh`

1. `geddit mininet/util/install.sh` or `vi mininet/util/install.sh` or `vim mininet/util/install.sh`

1. search for `git clone`

1. replace `git clone git://openflowswitch.org/openflow.git` with `git clone https://github.com/mininet/openflow.git`

1. rerun `./mininet/util/install.sh -fn03`
