### ISSUE TITLE
command "vagrant up" failed 

### ISSUE THREAD

**Issue by ovntatar** [PrincetonUniversity/Coursera-SDN#61]
If I try to run basics command from README get the following error 

```

> Coursera-SDN  $ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Box 'coursera-sdn-2015.box' could not be found. Attempting to find and install...
    default: Box Provider: libvirt
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'coursera-sdn-2015.box' (v0) for provider: libvirt
    default: Downloading: https://d396qusza40orc.cloudfront.net/sdn1/srcs/Vagrant%20Box/coursera-sdn-2015_32bit.box
The box you attempted to add doesn't match the provider you specified.

Provider expected: libvirt
Provider of box: virtualbox
```

virtualbox 6.1 is already installed on my OS "fedora release 31 (Thirty One)" 

Oracle VM VirtualBox VM Runner v6.1.16_RPMFusion
(C) 2005-2020 Oracle Corporation
All rights reserved.

the software run at: 
```
uname -a
Linux xxx.xxx.xxx 5.8.18-100.fc31.x86_64 #1 SMP Mon Nov 2 20:32:55 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
tried the same with 64 bit Vagrant Box but get same issue , have you any idea how to fix it ?

**Comment by ARCHAJ** [comment]
same issue on windows!!

**Comment by AndhikaWB** [comment]
Change provider to VirtualBox or whatever hypervisor you installed (e.g. `vagrant up --provider=virtualbox`). Libvirt is usually for QEMU. You can use `vagrant mutate` or convert VMDK inside the box directly to boot it on other hypervisor.
